var head    = '  <meta charset="utf-8">\n<meta http-equiv="X-UA-Compatible" content="IE=edge">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<meta name="description" content="">  \n<meta name="author" content="">  \n<title>Jordy Ferreira</title>\n\n<!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->\n<link href="css/bootstrap.min.css" rel="stylesheet">  \n<!-- Custom CSS -->\n<link href="css/freelancer.css" rel="stylesheet">\n\n\n<!-- Custom Fonts -->\n<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">\n<link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">\n<link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">\n\n<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries --><!-- WARNING: Respond.js doesnt work if you view the page via file: --><!--[if lt IE 9]><script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script><script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script><![endif]-->'
var header  = '  <!-- Navigation -->\n    <nav class="navbar navbar-default navbar-fixed-top">\n        <div class="container">\n            <!-- Brand and toggle get grouped for better mobile display -->\n            <div class="navbar-header page-scroll">\n                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">\n                    <span class="sr-only">Toggle navigation</span>\n                    <span class="icon-bar"></span>\n                    <span class="icon-bar"></span>\n                    <span class="icon-bar"></span>\n                </button>\n                <a class="navbar-brand" href="#page-top" id="brand">Jordy Ferreira</a>\n            </div>\n\n            <!-- Collect the nav links, forms, and other content for toggling -->\n            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">\n                <ul class="nav navbar-nav navbar-right">\n                    <li class="hidden">\n                        <a href="#page-top"></a>\n                    </li>\n                    <li class="page-scroll">\n                        <a href="#portfolio" id="portfolio">Portfolio</a>\n                    </li>\n                    <li class="page-scroll">\n                        <a href="#about" id="about">About</a>\n                    </li>\n                    <li class="page-scroll">\n                        <a href="#contact" id="contact">Contact</a>\n                    </li>\n                </ul>\n            </div>\n            <!-- /.navbar-collapse -->\n        </div>\n        <!-- /.container-fluid -->\n    </nav>'
var scripts = '<!-- jQuery --><script src="js/jquery.js"></script>\n<!-- Bootstrap Core JavaScript -->\n<script src="js/bootstrap.min.js"></script>\n<!-- Plugin JavaScript -->\n<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>\n<script src="js/classie.js"></script>\n<script src="js/cbpAnimatedHeader.js"></script>\n<!-- Contact Form JavaScript --><script src="js/jqBootstrapValidation.js"></script>\n<script src="js/contact_me.js"></script><!-- Custom Theme JavaScript --><script src="js/freelancer.js"></script>'


// Exports
module.exports.head    = head
module.exports.header  = header
module.exports.scripts = scripts
