/* TO remove line break for \n
* sed -i ':a;N;$!ba;s/\n/\\n/g' text.txt
*/
var head          = '\n  <meta charset="utf-8">\n<meta http-equiv="X-UA-Compatible" content="IE=edge">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<meta name="description" content="">  \n<meta name="author" content="">  \n<title>Jordy Ferreira</title>\n\n<!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->\n<link href="css/bootstrap.min.css" rel="stylesheet">  \n<!-- Custom CSS -->\n<link href="css/freelancer.css" rel="stylesheet">\n\n\n<!-- Custom Fonts -->\n<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">\n<link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">\n<link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">\n\n<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries --><!-- WARNING: Respond.js doesnt work if you view the page via file: --><!--[if lt IE 9]><script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script><script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script><![endif]-->'
var navigation    = '\n  <!-- Navigation -->\n    <nav class="navbar navbar-default navbar-fixed-top">\n        <div class="container">\n            <!-- Brand and toggle get grouped for better mobile display -->\n            <div class="navbar-header page-scroll">\n                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">\n                    <span class="sr-only">Toggle navigation</span>\n                    <span class="icon-bar"></span>\n                    <span class="icon-bar"></span>\n                    <span class="icon-bar"></span>\n                </button>\n                <a class="navbar-brand" href="#page-top" id="brand">Jordy Ferreira</a>\n            </div>\n\n            <!-- Collect the nav links, forms, and other content for toggling -->\n            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">\n                <ul class="nav navbar-nav navbar-right">\n                    <li class="hidden">\n                        <a href="#page-top"></a>\n                    </li>\n                    <li class="page-scroll">\n                        <a href="#portfolio" >Portfolio</a>\n                    </li>\n                    <li class="page-scroll">\n                        <a href="#about" >Sobre</a>\n                    </li>\n <li class="page-scroll">\n                        <a href="#footer" >Contato</a>\n                    </li>\n                            </ul>\n            </div>\n            <!-- /.navbar-collapse -->\n        </div>\n        <!-- /.container-fluid -->\n    </nav>'
var header        = '\n  <!-- Header -->\n    <header>\n        <div class="container">\n            <div class="row">\n                <div class="col-lg-12">\n                    <img class="img-responsive" src="img/profile.png" alt="">\n                    <div class="intro-text">\n                        <span class="name" id="name">Jordy Ferreira</span>\n                        <hr class="star-light">\n                        <span class="skills" id="skills">Backend - Mobile - Frontend Programmer</span>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </header>'
var scripts       = '\n   <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->\n    <div class="scroll-top page-scroll visible-xs visible-sm">\n        <a class="btn btn-primary" href="#page-top">\n            <i class="fa fa-chevron-up"></i>\n        </a>\n    </div> \n\n\n<!-- jQuery --><script src="js/jquery.js"></script>\n<!-- Bootstrap Core JavaScript -->\n<script src="js/bootstrap.min.js"></script>\n<!-- Plugin JavaScript -->\n<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>\n<script src="js/classie.js"></script>\n<script src="js/cbpAnimatedHeader.js"></script>\n<!-- Contact Form JavaScript --><script src="js/jqBootstrapValidation.js"></script>\n<script src="js/contact_me.js"></script><!-- Custom Theme JavaScript --><script src="js/freelancer.js"></script>'
var portfolioGrid = '\n    <!-- Portfolio Grid Section -->\n    <section id="portfolio">\n        <div class="container">\n            <div class="row">\n                <div class="col-lg-12 text-center">\n                    <h2>Portfolio</h2>\n                    <hr class="star-primary">\n                </div>\n            </div>\n            <div class="row" id="portfolio-row">\n          \n            </div>\n        </div>\n    </section>'
var portfolioCell = '\n  <div class="col-sm-4 portfolio-item">\n                    <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">\n                        <div class="caption">\n                            <div class="caption-content">\n                                <i class="fa fa-search-plus fa-3x"></i>\n                            </div>\n                        </div>\n                        <img src="img/portfolio/imagename.png" class="img-responsive" alt="">\n                    </a>\n                </div>'
var portfolioModal= '\n    <div class="portfolio-modal modal fade" id="portfolioModal" tabindex="-1" role="dialog" aria-hidden="true">\n        <div class="modal-content">\n            <div class="close-modal" data-dismiss="modal">\n                <div class="lr">\n                    <div class="rl">\n                    </div>\n                </div>\n            </div>\n            <div class="container">\n                <div class="row">\n                    <div class="col-lg-8 col-lg-offset-2">\n                        <div class="modal-body">\n                            <h2>Project Title</h2>\n                            <hr class="star-primary">\n                            <img src="img/portfolio/submarine.png" class="img-responsive img-centered" alt="">\n                            <p></p>\n                            <ul class="list-inline item-details">\n                                <li>Client:\n                                    <strong><a href="http://startbootstrap.com">Start Bootstrap</a>\n                                    </strong>\n                                </li>\n                                <li>Date:\n                                    <strong><a href="http://startbootstrap.com">April 2014</a>\n                                    </strong>\n                                </li>\n                                <li>Service:\n                                    <strong><a href="http://startbootstrap.com">Web Development</a>\n                                    </strong>\n                                </li>\n                            </ul>\n                            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>\n                        </div>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>'
var about         = '\n    <!-- About Section -->\n    <section class="success" id="about">\n        <div class="container">\n            <div class="row">\n                <div class="col-lg-12 text-center">\n                    <h2>Sobre</h2>\n                    <hr class="star-light">\n                </div>\n            </div>\n            <div class="row">\n                <div class="text-center">\n                    <p id="about-text"></p>\n                </div>\n                           <div class="col-lg-8 col-lg-offset-2 text-center">\n       </div>\n        </div>\n    </section>'
var footer        = '\n    <!-- Footer -->\n    <footer id="footer" class="text-center">\n        <div class="footer-above">\n            <div class="container">\n                <div class="row">\n                    <div class="footer-col col-md-4">\n                        <h3>Localização</h3>\n                        <p>Fortaleza, Ceará</p>\n                    </div>\n                    <div class="footer-col col-md-4">\n                        <h3>Contato</h3>\n                        <ul class="list-inline" id="contact-table">\n                        </ul>\n                    </div>\n                    <div class="footer-col col-md-4">\n                        <h3>About Freelancer</h3>\n                        <p>Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.</p>\n                    </div>\n                </div>\n            </div>\n        </div>\n        <div class="footer-below">\n            <div class="container">\n                <div class="row">\n                    <div class="col-lg-12">\n                        Copyright &copy; Jordy Ferreira 2016\n                    </div>\n                </div>\n            </div>\n        </div>\n    </footer>'
var contactCell  = '\n<a href="#" class="btn-social btn-outline"><i class="fa fa-fw"></i></a>\n'

// Exports
module.exports.head           = head
module.exports.navigation     = navigation
module.exports.header         = header
module.exports.scripts        = scripts
module.exports.portfolioGrid  = portfolioGrid
module.exports.portfolioCell  = portfolioCell
module.exports.portfolioModal = portfolioModal
module.exports.about          = about
module.exports.footer         = footer
module.exports.contactCell    = contactCell
